import 'dart:io';
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:mifi_rental/res/strings.dart';
import 'package:mifi_rental/util/shared_preferences_util.dart';

class MyLocalizations {
  MyLocalizations(this.locale);
  final Locale locale;

  static MyLocalizations of(BuildContext context) {
    return Localizations.of<MyLocalizations>(context, MyLocalizations);
  }

  String getLanguage() {
    String languageCode = locale.languageCode;
    String countryCode = locale.countryCode;
    if (Platform.isIOS) {
      languageCode = SharedPreferenceUtil.nativeLocal.languageCode;
      countryCode = SharedPreferenceUtil.nativeLocal.countryCode;

      if (languageCode.contains('zh')) {
        return 'zh-${countryCode}';
      } else {
        return 'en-US';
      }
    } else {
      switch (languageCode) {
        case 'zh':
          return 'zh-${countryCode}';
        default:
          return 'en-US';
      }
    }
  }

  String getString(int id) {
    String languageCode = locale.languageCode;
    String countryCode = locale.countryCode;
    String value;
    if (Platform.isIOS) {
      languageCode = SharedPreferenceUtil.nativeLocal.languageCode;
      countryCode = SharedPreferenceUtil.nativeLocal.countryCode;

      if (languageCode.contains('zh')) {
        value = _localizedZH[countryCode][id];
      } else {
        value = __localizedEN[id];
      }
    } else {
      switch (languageCode) {
        case 'en':
          value = __localizedEN[id];
          break;
        case 'zh':
          value = _localizedZH[countryCode][id];
          break;
        default:
          value = __localizedEN[id];
      }
    }
    return value != null ? value : '';
  }

  static Map<int, String> __localizedEN = {
    home_page: 'Home',
    user_agreement: 'User Agreement',
    privacy_policy: 'Privacy Policy',
    scan_wifi_rental: 'Scan the QR Code displayed on the cabinet',
    scan: 'Scan',
    agree: 'I agree',
    disagree: 'Cancel',
    last_update: 'Last refresh time:',
    refresh: 'Refresh',
    surplus_data: 'Data remaining',
    buy_data: 'You are running out of data allowance, buy more data add-on',
    lease_duration: 'Rental period',
    buckle_amount: 'Pre-paid amount',
    lease_date: 'Device rented',
    device_deposit: 'Deposit',
    if_like_device: 'If you like this device, you can also:',
    buy_this_device: 'Keep it',
    buy_new_device: 'Buy a new one',
    device_info: 'Device information',
    wifi_name: 'WiFi SSID',
    wifi_password: 'WIFI Password',
    imei: 'IMEI',
    trouble_report: 'Report a fault',
    pay: 'Pay',
    paypal: 'Paypal',
    pay_type: 'Payment method',
    paypal_tip: 'e-Cheque and Wire transfer are not supported.',
    lease_tip: 'Rules of rental',
    expend_all: 'Expend all',
    pay_amount: 'Rent total',
    go_pay: 'Checkout',
    buckle_tip: 'After your return the device, the rental fees will be deducted from deposit, and the remaining deposit will be refunded to your original payment method.',
    problem: 'FAQs',
    rent_fail: 'Rent failed',
    pay_fail: 'Pay failed',
    pay_fail_tip: 'Failed to pay successfully, please pay again',
    repay: 'Please pay again',
    flow_package: 'Data add-on',
    choose_package: 'Select data add-on',
    notice_for_use: 'Usage terms',
    rent_success: 'Success',
    no_rent_device: 'No rentable MiFi',
    no_rent_device_detail: 'Sorry, there is no rental MiFi in the cabinet!',
    return_home: 'Back to home page',
    device_pop_up: 'The device has been ejected',
    take_your_equipment: 'Please take your device. Have a good trip!',
    check_device_information: 'View device information',
    rent_tip: 'Please check your device within 5 minutes upon pick up. If it is a faulty device, click on "Report a fault" and insert it back after submission. No charges would occur during the process.',
    confirm: 'Confirm',
    return_success:'Return successfully',
    hours:'h',
    minutes:'m',
    network_exceptions:'Network exception',
    tips:'Tips',
    please_wait:'MiFi is being ejected, please wait , thanks!',
    popup_timeout_title: 'Pop up timeout',
    popup_timeout_message: ' If the MiFi has been ejected, please take it away for use. If the MiFi does not pop up, please do not go away, contact customer service in time!',
    popup_failure: 'Pop up failure',
    popup_failure_message: 'Pop-up MiFi failure or no suitable MiFi to borrow',
    e00000003:'loginCustomerId is null',
    e00000006:'accessToke is null',
    e00000007:'accessToken is expire',
    e00000008:'accessToken does not belong to the loginCustomer',
    e00000022:'may not be null',
    e00000023:'range must in [-180,180]',
    e00000024:'range must in [-90,90]',
    e00000025:'not defined, must be one of {definedValues}',
    e00000026:'may not be empty',
    e00000027:'length must be between {min} and {max}',
    e00000028:'size must be between {min} and {max}',
    e00000029:'must match “{regexp}”',
    e00000030:'not a well-formed email address',
    e00000031:'not a correct timestamp format, must be between {min} and {max}',
    e00000032:'must be a digit',
    e00000044:'data exists',
    e00000045:'data not exists',
    e00000046:'You have no permission to access the data',
    e00000047:'TOKEN CHECK ERROR',
    e99999999:'Fail',
    e02000100:'exists unfinished order',
    e02000101:'order not pay',
    e02000102:'can’t cancel order, please check order status.',
    e02000103:'operation time out , please rescan QR code.',
    e02000104:'before order not finished.',
    e02000105:'order is handling.',
    e02000106:'order pay failed.',
    e02000200:'terminal is offline.',
    e02000201:'repeat pop up request.',
    e02000202:'can’t delete bank, it’s still has terminal under this bank.',
    e02000300:'there is no mifi available.',
    e02000301:'there is no power mifi available.',
    e02000302:'pop up mifi failed.',
  };

  static Map<String, Map<int, String>> _localizedZH = {
    'CN': {
      home_page: '首页',
      user_agreement: '用户协议',
      privacy_policy: '隐私政策',
      scan_wifi_rental: '请扫描面包机上的二维码租赁设备',
      scan: '扫一扫',
      agree: '同意',
      disagree: '不同意',
      last_update: '上次刷新时间:',
      refresh: '刷新',
      surplus_data: '剩余流量',
      buy_data: '流量不够，去购买加油包',
      lease_duration: '租赁时长',
      buckle_amount: '应付金额',
      lease_date: '租赁时间',
      device_deposit: '设备押金',
      if_like_device: '如果您喜欢这个设备，您还可以:',
      buy_this_device: '拥有此设备',
      buy_new_device: '购买新设备',
      device_info: '设备信息',
      wifi_name: 'WIFI名称',
      wifi_password: 'WIFI密码',
      imei: 'IMEI',
      trouble_report: '故障申报',
      pay: '支付',
      paypal: 'Paypal',
      pay_type: '支付方式',
      paypal_tip: '由于Paypal的认证机制，请不要用电子支票和银行转账。',
      lease_tip: '租赁使用规则',
      expend_all: '展开全部',
      pay_amount: '支付金额',
      go_pay: '去支付',
      buckle_tip: '还机后剩余押金将自动原路退还',
      problem: '常见问题',
      rent_fail: '租赁失败',
      pay_fail: '支付失败',
      pay_fail_tip: '未支付成功，请重新支付',
      repay: '重新支付',
      flow_package: '加油包',
      choose_package: '选择加油包',
      notice_for_use: '使用须知',
      rent_success: '租赁成功',
      no_rent_device: '无可租设备',
      no_rent_device_detail: '非常抱歉，机器内已无可租设备！',
      return_home: '返回首页',
      device_pop_up: '设备已弹出',
      take_your_equipment: '请拿好您的设备,开机即可享受WIFI服务!',
      check_device_information: '查看设备信息',
      rent_tip:
          '获取设备后请在5分钟内进行检查，如果发现有问题请点击“故障申告”进行反馈，反馈完毕后请将设备插回机器空置仓位，此期间不计费。',
      confirm: '确定',
      return_success:'归还成功',
      hours:'时',
      minutes:'分',
      network_exceptions:'网络异常',
      tips:'提示',
      please_wait:'正在弹出设备，请稍候...',
      popup_timeout_title: '弹机超时',
      popup_timeout_message: '如果设备已弹出，请取走使用。如果设备未弹出，请不要走开，及时联系客服！',
      popup_failure: '弹机失败',
      popup_failure_message: '弹机失败或是无合适设备可借',
      e00000003:'登陆客户id为null',
      e00000006:'accessToke 为null',
      e00000007:'accessToke 过期',
      e00000008:'accessToke 不属于当前登陆用户',
      e00000022:'参数不能为null',
      e00000023:'范围必须在[-180,180]之间',
      e00000024:'范围必须在[-90,90]之间',
      e00000025:'参数未定义默认值',
      e00000026:'参数不能为空',
      e00000027:'参数长度必须在之间',
      e00000028:'参数大小必须在之间',
      e00000029:'参数需要匹配正则表达式',
      e00000030:'邮箱格式不正确',
      e00000031:'时间戳格式不正确',
      e00000032:'参数必须为数字',
      e00000044:'数据已存在',
      e00000045:'数据不存在',
      e00000046:'没有数据访问权限',
      e00000047:'token验证错误',
      e99999999:'失败',
      e02000100:'存在未完成的订单',
      e02000101:'订单未支付',
      e02000102:'不能取消订单，检查订单状态',
      e02000103:'操作超时，请重新扫码下单',
      e02000104:'前一个订单正在进行，请稍等',
      e02000105:'订单正在处理中，请稍等',
      e02000106:'订单支付失败',
      e02000200:'机柜离线',
      e02000201:'重复的弹出请求',
      e02000202:'该网点下还有机柜信息，不能删除',
      e02000300:'没有设备可用',
      e02000301:'没有设备可用(电量不足)',
      e02000302:'设备弹出失败',
    },
    'HK': {
      home_page: '首頁',
      user_agreement: '用戶協議',
      privacy_policy: '隱私政策',
      scan_wifi_rental: '請掃描面包機上的二維碼租賃設備',
      scan: '掃一掃',
      agree: '同意',
      disagree: '不同意',
      last_update: '上次刷新時間:',
      refresh: '刷新',
      surplus_data: '剩余流量',
      buy_data: '流量不夠，去購買加油包',
      lease_duration: '租賃時長',
      buckle_amount: '應付金額',
      lease_date: '租賃時間',
      device_deposit: '設備押金',
      if_like_device: '如果您喜歡這個設備，您還可以:',
      buy_this_device: '擁有此設備',
      buy_new_device: '購買新設備',
      device_info: '設備信息',
      wifi_name: 'WIFI名稱',
      wifi_password: 'WIFI密碼',
      imei: 'IMEI',
      trouble_report: '故障申報',
      pay: '支付',
      paypal: 'Paypal',
      pay_type: '支付方式',
      paypal_tip: '由於Paypal的認證機制，請不要用電子支票和銀行轉賬。',
      lease_tip: '租賃使用規則',
      expend_all: '展開全部',
      pay_amount: '支付金額',
      go_pay: '去支付',
      buckle_tip: '還機後剩余押金將自動原路退還',
      problem: '常見問題',
      rent_fail: '租賃失敗',
      pay_fail: '支付失敗',
      pay_fail_tip: '未支付成功，請重新支付',
      repay: '重新支付',
      flow_package: '加油包',
      choose_package: '選擇加油包',
      notice_for_use: '使用須知',
      rent_success: '租賃成功',
      no_rent_device: '無可租設備',
      no_rent_device_detail: '非常抱歉，機器內已無可租設備！',
      return_home: '返回首頁',
      device_pop_up: '設備已彈出',
      take_your_equipment: '請拿好您的設備,開機即可享受WIFI服務!',
      check_device_information: '查看設備信息',
      rent_tip:
          '獲取設備後請在5分鐘內進行檢查，如果發現有問題請點擊“故障申告”進行反饋，反饋完畢後請將設備插回機器空置倉位，此期間不計費。',
      confirm: '確認',
      return_success:'歸還成功',
      hours:'時',
      minutes:'分',
      network_exceptions:'網絡異常',
      tips:'提示',
      please_wait:'正在彈出設備，請稍候...',
      popup_timeout_title: '彈機超時',
      popup_timeout_message: '如果設備已彈出，請取走使用。如果設備未彈出，請不要走開，及時聯繫客服！',
      popup_failure: '彈機失敗',
      popup_failure_message: '彈機失敗或是無合適設備可借',
      e00000003:'登陆客户id为null',
      e00000006:'accessToke 为null',
      e00000007:'accessToke 过期',
      e00000008:'accessToke 不属于当前登陆用户',
      e00000022:'参数不能为null',
      e00000023:'范围必须在[-180,180]之间',
      e00000024:'范围必须在[-90,90]之间',
      e00000025:'参数未定义默认值',
      e00000026:'参数不能为空',
      e00000027:'参数长度必须在之间',
      e00000028:'参数大小必须在之间',
      e00000029:'参数需要匹配正则表达式',
      e00000030:'邮箱格式不正确',
      e00000031:'时间戳格式不正确',
      e00000032:'参数必须为数字',
      e00000044:'数据已存在',
      e00000045:'数据不存在',
      e00000046:'没有数据访问权限',
      e00000047:'token验证错误',
      e99999999:'失败',
      e02000100:'存在未完成的订单',
      e02000101:'订单未支付',
      e02000102:'不能取消订单，检查订单状态',
      e02000103:'操作超时，请重新扫码下单',
      e02000104:'前一个订单正在进行，请稍等',
      e02000105:'订单正在处理中，请稍等',
      e02000106:'订单支付失败',
      e02000200:'机柜离线',
      e02000201:'重复的弹出请求',
      e02000202:'该网点下还有机柜信息，不能删除',
      e02000300:'没有设备可用',
      e02000301:'没有设备可用(电量不足)',
      e02000302:'设备弹出失败',
    },
    'TW': {
      home_page: '首頁',
      user_agreement: '用戶協議',
      privacy_policy: '隱私政策',
      scan_wifi_rental: '請掃描面包機上的二維碼租賃設備',
      scan: '掃一掃',
      agree: '同意',
      disagree: '不同意',
      last_update: '上次刷新時間:',
      refresh: '刷新',
      surplus_data: '剩余流量',
      buy_data: '流量不夠，去購買加油包',
      lease_duration: '租賃時長',
      buckle_amount: '應付金額',
      lease_date: '租賃時間',
      device_deposit: '設備押金',
      if_like_device: '如果您喜歡這個設備，您還可以:',
      buy_this_device: '擁有此設備',
      buy_new_device: '購買新設備',
      device_info: '設備信息',
      wifi_name: 'WIFI名稱',
      wifi_password: 'WIFI密碼',
      imei: 'IMEI',
      trouble_report: '故障申報',
      pay: '支付',
      paypal: 'Paypal',
      pay_type: '支付方式',
      paypal_tip: '由於Paypal的認證機制，請不要用電子支票和銀行轉賬。',
      lease_tip: '租賃使用規則',
      expend_all: '展開全部',
      pay_amount: '支付金額',
      go_pay: '去支付',
      buckle_tip: '還機後剩余押金將自動原路退還',
      problem: '常見問題',
      rent_fail: '租賃失敗',
      pay_fail: '支付失敗',
      pay_fail_tip: '未支付成功，請重新支付',
      repay: '重新支付',
      flow_package: '加油包',
      choose_package: '選擇加油包',
      notice_for_use: '使用須知',
      rent_success: '租賃成功',
      no_rent_device: '無可租設備',
      no_rent_device_detail: '非常抱歉，機器內已無可租設備！',
      return_home: '返回首頁',
      device_pop_up: '設備已彈出',
      take_your_equipment: '請拿好您的設備,開機即可享受WIFI服務!',
      check_device_information: '查看設備信息',
      rent_tip:
          '獲取設備後請在5分鐘內進行檢查，如果發現有問題請點擊“故障申告”進行反饋，反饋完畢後請將設備插回機器空置倉位，此期間不計費。',
      confirm: '確認',
      return_success:'歸還成功',
      hours:'時',
      minutes:'分',
      network_exceptions:'網絡異常',
      tips:'提示',
      please_wait:'正在彈出設備，請稍候...',
      popup_timeout_title: '彈機超時',
      popup_timeout_message: '如果設備已彈出，請取走使用。如果設備未彈出，請不要走開，及時聯繫客服！',
      popup_failure: '彈機失敗',
      popup_failure_message: '彈機失敗或是無合適設備可借',
      e00000003:'登陆客户id为null',
      e00000006:'accessToke 为null',
      e00000007:'accessToke 过期',
      e00000008:'accessToke 不属于当前登陆用户',
      e00000022:'参数不能为null',
      e00000023:'范围必须在[-180,180]之间',
      e00000024:'范围必须在[-90,90]之间',
      e00000025:'参数未定义默认值',
      e00000026:'参数不能为空',
      e00000027:'参数长度必须在之间',
      e00000028:'参数大小必须在之间',
      e00000029:'参数需要匹配正则表达式',
      e00000030:'邮箱格式不正确',
      e00000031:'时间戳格式不正确',
      e00000032:'参数必须为数字',
      e00000044:'数据已存在',
      e00000045:'数据不存在',
      e00000046:'没有数据访问权限',
      e00000047:'token验证错误',
      e99999999:'失败',
      e02000100:'存在未完成的订单',
      e02000101:'订单未支付',
      e02000102:'不能取消订单，检查订单状态',
      e02000103:'操作超时，请重新扫码下单',
      e02000104:'前一个订单正在进行，请稍等',
      e02000105:'订单正在处理中，请稍等',
      e02000106:'订单支付失败',
      e02000200:'机柜离线',
      e02000201:'重复的弹出请求',
      e02000202:'该网点下还有机柜信息，不能删除',
      e02000300:'没有设备可用',
      e02000301:'没有设备可用(电量不足)',
      e02000302:'设备弹出失败',
    }
  };
}
